# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Java CI with Gradle

on:
  # Trigger the workflow on push
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build -x test
    - name: Publish Packages to Sonotype
      run: ./gradlew -Pversion="${githubRef#refs/tags/}" -PbuildNumber="${buildNumber}" sign publishMavenPublicationToSonatypeRepository
      env:
        githubRef: ${{ github.ref }}
        buildNumber: ${{ github.run_number }}
        ORG_GRADLE_PROJECT_signingKey: ${{secrets.signingKey}}
        ORG_GRADLE_PROJECT_signingPassword: ${{secrets.signingPassword}}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{secrets.sonatypeUsername}}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{secrets.sonatypePassword}}
